#%RAML 1.0 Trait
# Borrowed from https://api.yaas.io/patterns/

usage: |
  Apply this trait to any GET method that supports content based caching (using ETags).
headers:
  If-None-Match:
    required: false
    type: string
    description: |
      This header requests to return the resource only if it does not match the given ETag. If the entity does match the provided ETag
      then HTTP 304 Not Modified status will be returned instead of requested resource.
    example: de305d54-75b4-431b-adb2-eb6b9e546014
responses:
  200:
    headers:
      ETag:
        description: |
          Entity Tag header containing a calculated tag (e.g. hash function.) which could be used for subsequent calls
        type: string
        example: de305d54-75b4-431b-adb2-eb6b9e546014
      Cache-Control:
        description: |
          Activates caching and defines cache behavior through cache response directives. 
          Usually defines public or private (cacheable by proxy or not) and max-age for resource.
          See http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html for more information.
        type: string
        example: private, max-age=31536000
  304:
    headers:
      ETag:
        description: |
          Entity Tag header containing a calculated tag (e.g. hash function.) which could be used for subsequent calls
        type: string
        example: de305d54-75b4-431b-adb2-eb6b9e546014
      Cache-Control:
        description: |
          Activates caching and defines cache behavior through cache response directives. 
          Usually defines public or private (cacheable by proxy or not) and max-age for resource.
          See http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html for more information.
        type: string
        example: private, max-age=31536000
    description:  |
      Entity has not been modified and the version cached by the client may be used.