#%RAML 1.0 Trait
description: Parameters and responses for records returned as a set of pages
usage: Apply to GET operations for resources that return collections

queryParameters:
  page:
    description: The page number requested, starting from 1
    type: integer
    required: false
    example: 20
    default: 1
  pageSize:
    description: The number of records per page
    type: integer
    required: false
    example: 5
    default: 20
